// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelProcessing() {
  return window['go']['main']['App']['CancelProcessing']();
}

export function ConfirmStep4(arg1) {
  return window['go']['main']['App']['ConfirmStep4'](arg1);
}

export function GetDefaultDir() {
  return window['go']['main']['App']['GetDefaultDir']();
}

export function PickDirectory() {
  return window['go']['main']['App']['PickDirectory']();
}

export function Quit() {
  return window['go']['main']['App']['Quit']();
}

export function ScanDirectory(arg1) {
  return window['go']['main']['App']['ScanDirectory'](arg1);
}

export function StartProcessing(arg1, arg2) {
  return window['go']['main']['App']['StartProcessing'](arg1, arg2);
}

export function Write(arg1) {
  return window['go']['main']['App']['Write'](arg1);
}
