// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CancelProcessing():Promise<void>;

export function ConfirmStep4(arg1:boolean):Promise<void>;

export function GetDefaultDir():Promise<string>;

export function PickDirectory():Promise<string>;

export function Quit():Promise<void>;

export function ScanDirectory(arg1:string):Promise<main.DirStats>;

export function StartProcessing(arg1:string,arg2:any):Promise<void>;

export function Write(arg1:Array<number>):Promise<number>;
